site_name: OmegaT for CAT Beginners
markdown_extensions:
  - tables
  - def_list
  - footnotes
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
theme:
  name: material
nav:
  - 'Index': 'index.md'
  - 'English': 'OmegaT_for_Beginners_en.md'
  - 'Japanese': 'OmegaT_for_Beginners_ja.md'
